### ISSUE TITLE
Why the trailing Verb variable?

### ISSUE THREAD

**Issue by ebissonn** [Pro/opcua-animal-cs#1]
![image](https://user-images.githubusercontent.com/51915159/64375679-5d8cf700-cff4-11e9-9d1b-401cae552728.png)

and with a datatype==Null

![image](https://user-images.githubusercontent.com/51915159/64376732-ee64d200-cff6-11e9-820a-f19057b6b758.png)

**Comment by Pro** [comment]
Verb is defined as mandatory on the base type in the information model, therefore it is created for every instance of an animal.

See also https://github.com/Pro/opcua-animal-cs/blob/0efcf38ea2ef0204e831c951e5578feec58dc634/animalModel.xml#L70

The null value comes from the issue here:
https://github.com/open62541/open62541/issues/2924

**Comment by Pro** [comment]
Feel free to open new issues if questions remain.
